Add files via upload
Not compiling. Need to add functionality for when the file is blank. Also have these errors currently reporting:
Traceback (most recent call last):
  File "basic_Address_book.py", line 106, in <module>
    main()
  File "basic_Address_book.py", line 85, in main
    app = ContactsInterface('contact.data')
  File "basic_Address_book.py", line 30, in __init__
    self.persons = pickle.load(person_list)
EOFError: Ran out of input
Exception ignored in: <bound method ContactsInterface.__del__ of <__main__.ContactsInterface object at 0x101105f98>>
Traceback (most recent call last):
  File "basic_Address_book.py", line 78, in __del__
    pickle.dump(self.persons, db1)
AttributeError: 'ContactsInterface' object has no attribute 'persons'